# Server settings
server:
    port: 8080
    servlet:
        context-path: /quick-cart

# Logging settings
logging:
    level:
        root: INFO

# Database configuration
spring:
    datasource:
        url: jdbc:h2:mem:quickcartdb
        username: sa
        password: password
        driver-class-name: org.h2.Driver
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
#        database-platform: org.h2.Driver
        hibernate:
            ddl-auto: update
        show-sql: true